### ISSUE TITLE
Amazing! one though on the extra buffers opned when using runner

### ISSUE THREAD

**Issue by zeltak** [thamer/runner#4]
Hi
Runner is amazing and seems to take care of many of the things i have been annoyed with in dired! thanks so much for this fantastic package!

i do have one question though. It seems that when i launch commands for media (such as VLC) etc there is a buffer that pops up and shows the CLI output. i read this:

If command string contains “{run:out}”, then keep output in a specially named buffer.
If command string contains “{run:shell}”, then run command using the function specified in runner-shell-function.
is there a way to similarly define not to open a buffer at all when I launch a command. i do have this in my config which dosent seem to help 

```
  (setq runner-run-in-background t
        runner-show-label        nil
        runner-shell-function   'runner-shell-function-eshell)
```

thanks again so much

Z

**Comment by thamer** [comment]
Try using the Customize interface when setting `runner-run-in-background`:

    M-x customize-variable runner-run-in-background 

Since `runner-run-in-background` is defined using `defcustom`, it isn't being set properly using `setq`. I'll see if I can find a way to fix this.

Thanks.

**Comment by thamer** [comment]
I've changed `runner-run-in-background` to a minor mode, which should be easier to set or toggle.

Closing.

Thanks.
